Add powerpool.io to template list
minershive/hive-pooltemplates pull request #1203
Opened 2022-10-23 11:53 UTC by JKK1

2022-10-23 14:04 UTC, HaloGenius commented
Please read README.md carefully - remove C++ style comments

2022-10-23 14:06 UTC, HaloGenius requested changes
remove C++ style comments

2022-10-23 14:10 UTC, JKK1 commented
Should be fixed now

2022-10-25 06:11 UTC, HaloGenius approved these changes

2022-10-25 06:23 UTC, merged